export {default as About} from "./About"
export {default as Cart} from "./Cart"
export {default as ErrorPage} from "./ErrorPage"
export {default as HomeLayout} from "./HomeLayout"
export {default as LandingPage} from "./LandingPage"
export {default as Products} from "./Products"
export {default as SingleProduct} from "./SingleProduct"
export {default as CategoryPage} from "./CategoryPage"